// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calc.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_calc_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_calc_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/service.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_calc_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_calc_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_calc_2eproto;
class CalcRequest;
struct CalcRequestDefaultTypeInternal;
extern CalcRequestDefaultTypeInternal _CalcRequest_default_instance_;
class CalcResponse;
struct CalcResponseDefaultTypeInternal;
extern CalcResponseDefaultTypeInternal _CalcResponse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class CalcResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CalcResponse) */ {
 public:
  inline CalcResponse() : CalcResponse(nullptr) {}
  ~CalcResponse() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalcResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline CalcResponse(const CalcResponse& from) : CalcResponse(nullptr, from) {}
  inline CalcResponse(CalcResponse&& from) noexcept
      : CalcResponse(nullptr, std::move(from)) {}
  inline CalcResponse& operator=(const CalcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalcResponse& operator=(CalcResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalcResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CalcResponse* internal_default_instance() {
    return reinterpret_cast<const CalcResponse*>(
        &_CalcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CalcResponse& a, CalcResponse& b) { a.Swap(&b); }
  inline void Swap(CalcResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalcResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalcResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<CalcResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalcResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalcResponse& from) { CalcResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CalcResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "CalcResponse"; }

 protected:
  explicit CalcResponse(::google::protobuf::Arena* arena);
  CalcResponse(::google::protobuf::Arena* arena, const CalcResponse& from);
  CalcResponse(::google::protobuf::Arena* arena, CalcResponse&& from) noexcept
      : CalcResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRetFieldNumber = 1,
  };
  // required int32 ret = 1;
  bool has_ret() const;
  void clear_ret() ;
  ::int32_t ret() const;
  void set_ret(::int32_t value);

  private:
  ::int32_t _internal_ret() const;
  void _internal_set_ret(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CalcResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CalcResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CalcResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t ret_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calc_2eproto;
};
// -------------------------------------------------------------------

class CalcRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CalcRequest) */ {
 public:
  inline CalcRequest() : CalcRequest(nullptr) {}
  ~CalcRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CalcRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline CalcRequest(const CalcRequest& from) : CalcRequest(nullptr, from) {}
  inline CalcRequest(CalcRequest&& from) noexcept
      : CalcRequest(nullptr, std::move(from)) {}
  inline CalcRequest& operator=(const CalcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalcRequest& operator=(CalcRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CalcRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CalcRequest* internal_default_instance() {
    return reinterpret_cast<const CalcRequest*>(
        &_CalcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CalcRequest& a, CalcRequest& b) { a.Swap(&b); }
  inline void Swap(CalcRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalcRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CalcRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<CalcRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CalcRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CalcRequest& from) { CalcRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CalcRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "CalcRequest"; }

 protected:
  explicit CalcRequest(::google::protobuf::Arena* arena);
  CalcRequest(::google::protobuf::Arena* arena, const CalcRequest& from);
  CalcRequest(::google::protobuf::Arena* arena, CalcRequest&& from) noexcept
      : CalcRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAFieldNumber = 1,
    kBFieldNumber = 2,
  };
  // required int32 a = 1;
  bool has_a() const;
  void clear_a() ;
  ::int32_t a() const;
  void set_a(::int32_t value);

  private:
  ::int32_t _internal_a() const;
  void _internal_set_a(::int32_t value);

  public:
  // required int32 b = 2;
  bool has_b() const;
  void clear_b() ;
  ::int32_t b() const;
  void set_b(::int32_t value);

  private:
  ::int32_t _internal_b() const;
  void _internal_set_b(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CalcRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CalcRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CalcRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t a_;
    ::int32_t b_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calc_2eproto;
};

// ===================================================================


// -------------------------------------------------------------------

class CalcService_Stub;
class CalcService : public ::google::protobuf::Service {
 protected:
  CalcService() = default;

 public:
  using Stub = CalcService_Stub;

  CalcService(const CalcService&) = delete;
  CalcService& operator=(const CalcService&) = delete;
  virtual ~CalcService() = default;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Add(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done);
  virtual void Subtract(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done);
  virtual void Multiply(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------
  const ::google::protobuf::ServiceDescriptor* GetDescriptor() override;

  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done) override;

  const ::google::protobuf::Message& GetRequestPrototype(
      const ::google::protobuf::MethodDescriptor* method) const override;

  const ::google::protobuf::Message& GetResponsePrototype(
      const ::google::protobuf::MethodDescriptor* method) const override;
};

class CalcService_Stub final : public CalcService {
 public:
  CalcService_Stub(::google::protobuf::RpcChannel* channel);
  CalcService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);

  CalcService_Stub(const CalcService_Stub&) = delete;
  CalcService_Stub& operator=(const CalcService_Stub&) = delete;

  ~CalcService_Stub() override;

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements CalcService ------------------------------------------
  void Add(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done) override;
  void Subtract(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done) override;
  void Multiply(::google::protobuf::RpcController* controller,
                        const ::CalcRequest* request,
                        ::CalcResponse* response,
                        ::google::protobuf::Closure* done) override;

 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
};
// ===================================================================



// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CalcRequest

// required int32 a = 1;
inline bool CalcRequest::has_a() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CalcRequest::clear_a() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t CalcRequest::a() const {
  // @@protoc_insertion_point(field_get:CalcRequest.a)
  return _internal_a();
}
inline void CalcRequest::set_a(::int32_t value) {
  _internal_set_a(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:CalcRequest.a)
}
inline ::int32_t CalcRequest::_internal_a() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.a_;
}
inline void CalcRequest::_internal_set_a(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.a_ = value;
}

// required int32 b = 2;
inline bool CalcRequest::has_b() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CalcRequest::clear_b() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t CalcRequest::b() const {
  // @@protoc_insertion_point(field_get:CalcRequest.b)
  return _internal_b();
}
inline void CalcRequest::set_b(::int32_t value) {
  _internal_set_b(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:CalcRequest.b)
}
inline ::int32_t CalcRequest::_internal_b() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.b_;
}
inline void CalcRequest::_internal_set_b(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.b_ = value;
}

// -------------------------------------------------------------------

// CalcResponse

// required int32 ret = 1;
inline bool CalcResponse::has_ret() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CalcResponse::clear_ret() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t CalcResponse::ret() const {
  // @@protoc_insertion_point(field_get:CalcResponse.ret)
  return _internal_ret();
}
inline void CalcResponse::set_ret(::int32_t value) {
  _internal_set_ret(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:CalcResponse.ret)
}
inline ::int32_t CalcResponse::_internal_ret() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ret_;
}
inline void CalcResponse::_internal_set_ret(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ret_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_calc_2eproto_2epb_2eh
