// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rpc_pkg.proto
// Protobuf C++ Version: 5.27.1

#include "rpc_pkg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr RpcPackage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        service_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        method_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pkg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pkg_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RpcPackage::RpcPackage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RpcPackageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RpcPackageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RpcPackageDefaultTypeInternal() {}
  union {
    RpcPackage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RpcPackageDefaultTypeInternal _RpcPackage_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rpc_5fpkg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rpc_5fpkg_2eproto = nullptr;
const ::uint32_t
    TableStruct_rpc_5fpkg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _impl_.service_name_),
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _impl_.method_name_),
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _impl_.pkg_size_),
        PROTOBUF_FIELD_OFFSET(::RpcPackage, _impl_.pkg_),
        0,
        1,
        3,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::RpcPackage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_RpcPackage_default_instance_._instance,
};
const char descriptor_table_protodef_rpc_5fpkg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rrpc_pkg.proto\"V\n\nRpcPackage\022\024\n\014service"
    "_name\030\001 \002(\t\022\023\n\013method_name\030\002 \002(\t\022\020\n\010pkg_"
    "size\030\003 \002(\005\022\013\n\003pkg\030\004 \002(\014"
};
static ::absl::once_flag descriptor_table_rpc_5fpkg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_rpc_5fpkg_2eproto = {
    false,
    false,
    103,
    descriptor_table_protodef_rpc_5fpkg_2eproto,
    "rpc_pkg.proto",
    &descriptor_table_rpc_5fpkg_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rpc_5fpkg_2eproto::offsets,
    file_level_enum_descriptors_rpc_5fpkg_2eproto,
    file_level_service_descriptors_rpc_5fpkg_2eproto,
};
// ===================================================================

class RpcPackage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<RpcPackage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000f) ^ 0x0000000f) != 0;
  }
};

RpcPackage::RpcPackage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RpcPackage)
}
inline PROTOBUF_NDEBUG_INLINE RpcPackage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::RpcPackage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        service_name_(arena, from.service_name_),
        method_name_(arena, from.method_name_),
        pkg_(arena, from.pkg_) {}

RpcPackage::RpcPackage(
    ::google::protobuf::Arena* arena,
    const RpcPackage& from)
    : ::google::protobuf::Message(arena) {
  RpcPackage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.pkg_size_ = from._impl_.pkg_size_;

  // @@protoc_insertion_point(copy_constructor:RpcPackage)
}
inline PROTOBUF_NDEBUG_INLINE RpcPackage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        service_name_(arena),
        method_name_(arena),
        pkg_(arena) {}

inline void RpcPackage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.pkg_size_ = {};
}
RpcPackage::~RpcPackage() {
  // @@protoc_insertion_point(destructor:RpcPackage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RpcPackage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.service_name_.Destroy();
  _impl_.method_name_.Destroy();
  _impl_.pkg_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RpcPackage::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              RpcPackage::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_._cached_size_),
              false,
          },
          &RpcPackage::MergeImpl,
          &RpcPackage::kDescriptorMethods,
          &descriptor_table_rpc_5fpkg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 42, 2> RpcPackage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RpcPackage_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RpcPackage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required bytes pkg = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.pkg_)}},
    // required string service_name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.service_name_)}},
    // required string method_name = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.method_name_)}},
    // required int32 pkg_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RpcPackage, _impl_.pkg_size_), 3>(),
     {24, 3, 0, PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.pkg_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string service_name = 1;
    {PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.service_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string method_name = 2;
    {PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.method_name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required int32 pkg_size = 3;
    {PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.pkg_size_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required bytes pkg = 4;
    {PROTOBUF_FIELD_OFFSET(RpcPackage, _impl_.pkg_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\12\14\13\0\0\0\0\0"
    "RpcPackage"
    "service_name"
    "method_name"
  }},
};

PROTOBUF_NOINLINE void RpcPackage::Clear() {
// @@protoc_insertion_point(message_clear_start:RpcPackage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.service_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.method_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.pkg_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.pkg_size_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RpcPackage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RpcPackage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string service_name = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_service_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "RpcPackage.service_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required string method_name = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_method_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "RpcPackage.method_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required int32 pkg_size = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_pkg_size(), target);
  }

  // required bytes pkg = 4;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_pkg();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RpcPackage)
  return target;
}

::size_t RpcPackage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RpcPackage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // required string service_name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_service_name());
    }

    // required string method_name = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_method_name());
    }

    // required bytes pkg = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_pkg());
    }

    // required int32 pkg_size = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_pkg_size());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RpcPackage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RpcPackage*>(&to_msg);
  auto& from = static_cast<const RpcPackage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RpcPackage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_service_name(from._internal_service_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_method_name(from._internal_method_name());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_pkg(from._internal_pkg());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.pkg_size_ = from._impl_.pkg_size_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RpcPackage::CopyFrom(const RpcPackage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RpcPackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RpcPackage::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const RpcPackage&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void RpcPackage::InternalSwap(RpcPackage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.service_name_, &other->_impl_.service_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.method_name_, &other->_impl_.method_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pkg_, &other->_impl_.pkg_, arena);
        swap(_impl_.pkg_size_, other->_impl_.pkg_size_);
}

::google::protobuf::Metadata RpcPackage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_rpc_5fpkg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
